---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: end-of-file-fixer
  - id: pretty-format-json
    args:
      - --autofix
  - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
  - id: go-fmt

- repo: local
  hooks:
  - id: go-mod-tidy
    name: go-mod-tidy
    language: system
    entry: make tidy
    pass_filenames: false
    always_run: true
    require_serial: true


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
